version: "3.7"

services:
  # app:
  #   build:
  #     context: .
  #   container_name: app
  #   env_file: ./.env
  #   depends_on:
  #     - mongo
  #   networks:
  #     - internal
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./server.js:/work/server.js
  #     - ./src:/work/src

  mongo:
    image: mongo:4.1.4-xenial
    container_name: mongo
    restart: always
    networks:
      - internal
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
    command: mongod
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: trung123
      MONGO_INITDB_DATABASE: myda

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongo
    restart: always
    networks:
      - internal
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: trung123

networks:
  internal:
    driver: bridge

volumes:
  mongo_data:
